Configurable id divider
zenstackhq/zenstack pull request #1785
Opened 2024-10-17 13:24 UTC by thomassnielsen

2024-10-17 18:51 UTC, ymc9 requested changes

2024-10-17 18:54 UTC, ymc9 commented
Hi @thomassnielsen , I've pushed a commit with the following changes:

- Update test to use postgres db
- Changes url pattern option from `segmentNameCharset` to `segmentValueCharset`
- Made sure ID key sent to Prisma is always joined with '_' instead of user-configured divider. I've renamed methods for clarity.

Please help check if they make sense. Thanks!

2024-10-18 07:04 UTC, thomassnielsen commented on packages/server/tests/api/rest.test.ts
> +                path: '/user/user1@abc.om:COMMON_USER',
That's a good idea. We might as well do that in this PR. Will look at it soon.

2024-10-18 23:12 UTC, ymc9 commented on packages/server/src/api/rest/index.ts
> +    urlSegmentNameCharset?: string;
Thinking about it again, I'll rename it to `urlSegmentCharSeet` for clarity. I'll make the change, merge the PR and make a new patch release. Thanks @thomassnielsen !

2024-10-19 03:46 UTC, ymc9 submitted a review, later dismissed

2024-10-19 04:24 UTC, merged