Update prettier v2 -> v3
zenstackhq/zenstack pull request #888
Opened 2023-12-11 20:03 UTC by sitch

2023-12-11 20:09 UTC, sitch commented on packages/plugins/trpc/package.json
> +        "@types/prettier": "^2.7.2"
prettier v3 exports ts types so for v3 you don't want to clobber those ts namespaces with the introduction of `@types/prettier`

2023-12-12 00:16 UTC, ymc9 requested changes

2023-12-13 06:17 UTC, ymc9 commented
Thank you! I'll resolve the conflicts and merge.

2023-12-13 16:34 UTC, sitch commented
> Thank you! I'll resolve the conflicts and merge.

You da man! :fire:  :1st_place_medal:

2023-12-14 06:58 UTC, ymc9 approved these changes

2023-12-14 07:15 UTC, merged